### ISSUE TITLE
Sugestões de implementação

### ISSUE THREAD

**Issue by abrantessouza** [gonribeiro/React-Battle-Rpg#1]
- Barra de life dos personagens
- Escolher golpes
- Função para aparecer o texto inteiro da história.

**Comment by gonribeiro** [comment]
- Função para aparecer o texto inteiro da história.:
Adicionei a possibilidade de acelerar ou desacelerar os textos da história. Me pareceu mais adequado a implementação dessa forma.

- Barra de life dos personagens
É bem simples fazer, mas vou ficar devendo ^^ (aqui tem um bom exemplo da implementação: https://github.com/gonribeiro/NLW-Rocketseat/tree/master/NLW4-Move.it).

- Escolher golpes
Tenho planejado uma versão online do jogo, essa sugestão será bem útil uma vez que as mecânicas atuais possam não ser interessante para batalhas online. Mas ainda levará um tempo até o lançamento.
